# Blueprint Metadata
blueprint:
  name: Controller - IKEA E2490 BILRESA remote control with scroll wheel
  description: |
    # Controller - IKEA E2490 BILRESA remote control with scroll wheel

    â„¹ï¸ Version 2026.02.28

    Controller automation for executing any kind of action triggered by the provided IKEA E2489 BILRESA remote control with buttons.
    Allows to optionally loop an action on a button long press.
    Supports Zigbee2MQTT.

    Automations created with this blueprint can be connected with one or more [Hooks](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/hooks) supported by this controller.
    Hooks allow to easily create controller-based automations for interacting with lights, covers, media players, and potentially more.
    See the list of [Hooks available for this controller](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2490/EPMatt/awesome/2026.02.28#available-hooks) for additional details.

    ## More Info

    ðŸ“ [Changelog](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2490/EPMatt/awesome/2026.02.28#changelog)
    ðŸ“• Full documentation regarding this blueprint is available [here](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/ikea_e2490).

    ðŸš€ This blueprint is part of the **[Awesome HA Blueprints](https://yarafie.github.io/awesome-ha-blueprints) project**. Please consider **[leaving a star on GitHub](https://github.com/yarafie/awesome-ha-blueprints)**! ðŸŒŸ

  source_url: https://github.com/yarafie/awesome-ha-blueprints/blob/main/blueprints/controllers/ikea_e2490/EPMatt/awesome/2026.02.28/ikea_e2490.yaml
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  # Device Selector
  input:
    controller_device:
      name: (Zigbee2MQTT Required) Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with Zigbee2MQTT, ZHA, deCONZ.
      default: ''
      selector:
        device:
          filter:
            # source: https://www.zigbee2mqtt.io/devices/E2490.html
            - integration: mqtt
              manufacturer: IKEA
              model: BILRESA remote control with scroll wheel
          multiple: false
    # inputs for custom actions
    action_button_up_short:
      name: (Optional) Up button short press
      description: Action to run on short up button press.
      default: []
      selector:
        action:
    action_button_up_double:
      name: (Optional) Up button double press
      description: Action to run on double up button press.
      default: []
      selector:
        action:
    action_button_down_short:
      name: (Optional) Down button short press
      description: Action to run on short down button press.
      default: []
      selector:
        action:
    action_button_down_double:
      name: (Optional) Down button double press
      description: Action to run on double down button press.
      default: []
      selector:
        action:
    action_rotate_wheel:
      name: (Optional) Rotate wheel
      description: Action to run on rotate wheel.
      default: []
      selector:
        action:
#
# Automation schema
variables:
  # Controller ID
  controller_id: !input controller_device
  # integration id used to select items in the action mapping
  # integration type is set from trigger.id
  integration_id: '{{ trigger.id.split("-")[0] }}'
  # convert input tags to variables, to be used in templates
  # mapping between actions and integrations
  actions_mapping:
    z2m:
      # source: https://www.zigbee2mqtt.io/devices/E2489.html
      button_up_short: ['on']
      button_up_double: [on_double]
      button_down_short: ['off']
      button_double_double: [off_double]
      rotate_wheel: [brightness_move_to_level]
  # pre-choose actions for buttons based on configured integration
  # mainly used to pass to hooks through ahb_controller_event
  button_up_short: '{{ actions_mapping[integration_id]["button_up_short"] }}'
  button_up_double: '{{ actions_mapping[integration_id]["button_up_double"] }}'
  button_down_short: '{{ actions_mapping[integration_id]["button_down_short"] }}'
  button_down_double: '{{ actions_mapping[integration_id]["button_down_double"] }}'
  rotate_wheel: '{{ actions_mapping[integration_id]["rotate_wheel"] }}'
#
# Mode Block
mode: single
max_exceeded: silent
#
# Triggers Block
triggers:
  # triggers for zigbee2mqtt
  # Up Button
  - trigger: device
    id: z2m-button-up-short
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'on'
  - trigger: device
    id: z2m-button-up-double
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: on_double
  # Down Button
  - trigger: device
    id: z2m-button-down-short
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: 'off'
  - trigger: device
    id: z2m-button-down-double
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: off_double
  # Rotate Wheel
  - trigger: device
    id: z2m-rotate-wheel
    domain: mqtt
    device_id: !input controller_device
    type: action
    subtype: brightness_move_to_level

#
# Conditions Block
conditions:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "z2m" -%}
        {{ trigger.payload }}
        {%- elif integration_id == "zha" -%}
        {{ trigger.event.data.command }}{{"_" if trigger.event.data.args|length > 0}}{{ trigger.event.data.args|join("_") }}
        {%- elif integration_id == "dcz" -%}
        {{ trigger.event.data.event }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None","unknown"] }}
#
# Actions Block
actions:
  #
  # choose the sequence to run based on the received button event
  - choose:
      #
      # Actions for Up Button single press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-up-short
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_short
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_up_short
      #
      # Actions for Down Button single press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-down-short
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_short
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_down_short
      #
      # Actions for Up Button double press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-dots1-double
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_up_double
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_up_double
      #
      # Actions for Down Button double press
      - conditions:
          - condition: trigger
            id:
              - z2m-button-down-double
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_down_double
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_down_double
      #
      # Actions for Rotate wheel
      - conditions:
          - condition: trigger
            id:
              - z2m-rotate-wheel
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: rotate_wheel
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_rotate_wheel
