# Blueprint Metadata
blueprint:
  name: Controller - Shelly SHBTN-2 Button 1
  description: |
    # Controller - Shelly SHBTN-2 Button 1

    Controller automation for executing any kind of action triggered by the provided Shelly SHBTN-2 Button 1.
    Allows to optionally loop an action on a button long press.
    Supports Shelly.

    Automations created with this blueprint can be connected with one or more [Hooks](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/hooks) supported by this controller.
    Hooks allow to easily create controller-based automations for interacting with lights, covers, media players, and potentially more.
    See the list of [Hooks available for this controller](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/shelly_shbtn_2#available-hooks) for additional details.

    ## More Info

    â„¹ï¸ Version 2025.03.25
    ðŸ“ [Changelog](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/shelly_shbtn_2/#changelog)
    ðŸ“• Full documentation regarding this blueprint is available [here](https://yarafie.github.io/awesome-ha-blueprints/docs/blueprints/controllers/shelly_shbtn_2).

    ðŸš€ This blueprint is part of the **[Awesome HA Blueprints](https://yarafie.github.io/awesome-ha-blueprints) project**. Please consider **[leaving a star on GitHub](https://github.com/EPMatt/awesome-ha-blueprints)**! ðŸŒŸ

  source_url: https://github.com/yarafie/awesome-ha-blueprints/blob/main/blueprints/controllers/shelly_shbtn_2/shelly_shbtn_2.yaml

  domain: automation
  homeassistant:
    min_version: 2024.10.0
  # Device Selector
  input:
    controller_device:
      name: (Required) (Shelly) Controller Device
      description: The controller device to use for the automation. Choose a value only if the remote is integrated with Shelly.
      default: ''
      selector:
        device:
          filter:
            # source: https://www.home-assistant.io/integrations/shelly
            - integration: shelly
              manufacturer: Shelly
              model: Shelly Button1
          multiple: false
    # inputs for custom actions
    action_button_button_short:
      name: (Optional) Button button short press
      description: Action to run on short button button press.
      default: []
      selector:
        action:
    action_button_button_long:
      name: (Optional) Button button long press
      description: Action to run on long button button press.
      default: []
      selector:
        action:
    action_button_button_release:
      name: (Optional) Button button release
      description: Action to run on button button release after long press.
      default: []
      selector:
        action:
    action_button_button_double:
      name: (Optional) Button button double press
      description: Action to run on double button button press.
      default: []
      selector:
        action:
    action_button_button_triple:
      name: (Optional) Button button triple press
      description: Action to run on triple button button press.
      default: []
      selector:
        action:
    # inputs for looping custom actions on long button press events until the corresponding release event is received
    long_press_options_section:
      name: Long Press options
      icon: mdi:remote
      collapsed: true
      input:
        button_button_long_loop:
          name: (Optional) Button button long press - loop until release
          description: Loop the button button action until the button is released.
          default: false
          selector:
            boolean:
        button_button_long_max_loop_repeats:
          name: (Optional) Button button long press - Maximum loop repeats
          description: >-
            Maximum number of repeats for the custom action, when looping is enabled.
            Use it as a safety limit to prevent an endless loop in case the corresponding stop event is not received.
          default: 20
          selector:
            number:
              min: 1.0
              max: 1000.0
              mode: slider
              step: 1.0
        helper_long_press_delay:
          name: (Optional) Helper - Long Press delay
          description: Max delay between the pushing and releasing of a button long press event. Increase this value if you notice that the long press action is not triggered properly.
          default: 250
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0
#
# Automation schema
variables:
  # Controller ID
  controller_id: !input controller_device
  # integration id used to select items in the action mapping
  # integration type is set from trigger.id
  integration_id: '{{ trigger.id.split("-")[0] }}'
  # convert input tags to variables, to be used in templates
  button_button_long_loop: !input button_button_long_loop
  button_button_long_max_loop_repeats: !input button_button_long_max_loop_repeats
  helper_long_press_delay: !input helper_long_press_delay
  # mapping between actions and integrations
  actions_mapping:
    sly:
      # source: https://www.home-assistant.io/integrations/shelly
      button_button_short: [single_1]
      button_button_long: [long_1]
      button_button_release: [long_single_1]
      button_button_double: [double_1]
      button_button_triple: [triple_1]
  # pre-choose actions for buttons based on configured integration
  # mainly used to pass to hooks through ahb_controller_event
  button_button_short: '{{ actions_mapping[integration_id]["button_button_short"] }}'
  button_button_long: '{{ actions_mapping[integration_id]["button_button_long"] }}'
  button_button_release: '{{ actions_mapping[integration_id]["button_button_release"] }}'
  button_button_double: '{{ actions_mapping[integration_id]["button_button_double"] }}'
  button_button_triple: '{{ actions_mapping[integration_id]["button_button_triple"] }}'
#
# Mode Block
mode: single
max_exceeded: silent
#
# Triggers Block
triggers:
  # triggers for Shelly
  - trigger: event
    id: sly-button-button-short
    event_type: shelly.click
    event_data:
      device_id: !input controller_device
      click_type: single
      channel: 1
  - trigger: event
    id: sly-button-button-long
    event_type: shelly.click
    event_data:
      device_id: !input controller_device
      click_type: long
      channel: 1
  - trigger: event
    id: sly-button-button-release
    event_type: shelly.click
    event_data:
      device_id: !input controller_device
      click_type: long_single
      channel: 1
  - trigger: event
    id: sly-button-button-double
    event_type: shelly.click
    event_data:
      device_id: !input controller_device
      click_type: double
      channel: 1
  - trigger: event
    id: sly-button-button-triple
    event_type: shelly.click
    event_data:
      device_id: !input controller_device
      click_type: triple
      channel: 1
#
# Conditions Block
conditions:
  - condition: and
    conditions:
      # check that the button event is not empty
      - >-
        {%- set trigger_action -%}
        {%- if integration_id == "sly" -%}
        {{ trigger.event.data.click_type }}
        {%- endif -%}
        {%- endset -%}
        {{ trigger_action not in ["","None","unknown"] }}
#
# Actions Block
actions:
  #
  # choose the sequence to run based on the received button event
  - choose:
      #
      # Actions for Button Button single press
      - conditions:
          - condition: trigger
            id:
              - sly-button-button-short
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_button_short
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_button_short
      #
      # Actions for Button Button Long Press
      - conditions:
          - condition: trigger
            id:
              - sly-button-button-long
        sequence:
          # fire the ahb event only once, the ahb hook will take care of looping
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_button_long
          # run the custom action only once before entering repeat
          - choose:
              - conditions: []
                sequence: !input action_button_button_long
          # handle custom action looping if looping is enabled
          - choose:
              - conditions: '{{ button_button_long_loop }}'
                sequence:
                  # Repeat the Long Press Actions for the set number of loops
                  - repeat:
                      count: !input button_button_long_max_loop_repeats
                      sequence:
                        - parallel:
                            - sequence: !input action_button_button_long
                            - sequence:
                                - choose:
                                    - conditions: []
                                      sequence:
                                        # Wait for z2m/zha/dcz triggers for Button Long Press Release to stop looping
                                        - wait_for_trigger:
                                            # sly triggers
                                            - trigger: event
                                              event_type: shelly.click
                                              event_data:
                                                device_id: !input controller_device
                                                click_type: long_single
                                                channel: 1
                                          timeout:
                                            milliseconds: !input helper_long_press_delay
                                          continue_on_timeout: true
                                        # If a Button Long Release is triggered wait.trigger.idx will be defined stop the loop before long_max_loop_repeats
                                        - if:
                                            - condition: template
                                              value_template: '{{ wait.trigger.idx is defined }}'
                                          then:
                                            - stop: button_button_released
      #
      # Actions for Button Button long press released
      - conditions:
          - condition: trigger
            id:
              - sly-button-button-release
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_button_release
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_button_release
      #
      # Actions for Button Button double press
      - conditions:
          - condition: trigger
            id:
              - sly-button-button-double
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_button_double
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_button_double
      #
      # Actions for Button Button triple press
      - conditions:
          - condition: trigger
            id:
              - sly-button-button-triple
        sequence:
          # fire the ahb hook event
          - event: ahb_controller_event
            event_data:
              controller: '{{ controller_id }}'
              action: button_button_triple
          # run the custom action
          - choose:
              - conditions: []
                sequence: !input action_button_button_triple
